### ISSUE TITLE
Go Mod confused by tag v0.8.3 update

### ISSUE THREAD

**Issue by chappy84** [cybergarage/go-net-upnp#4]
Go by default uses https://proxy.golang.org/ to download copies of packages, to cache any releases in-case there is an issue with the source server.

After the original release of v0.8.3, before my updates in #3, this was cached: https://proxy.golang.org/github.com/cybergarage/go-net-upnp/@v/v0.8.3.zip

Anyone using the `go mod` command will get this old v0.8.3 of the module:
https://stackoverflow.com/questions/61287518/how-to-handle-changed-remote-tag-with-go-modules
without modifying their related GO environment variables (e.g. `GOPRIVATE`, `GOPROXY`, `GOSUMDB`)

Could I suggest you retract v0.8.3, and release a v0.8.4, in-line with this: https://proxy.golang.org/#faq-retract-version so that there is no difference between the tagged version on github, and the cached version provided by proxy.golang.org ?

**Comment by cybergarage** [comment]
@chappy84 Thanks for your report.
I have released the latest version as v0.8.4 now. Please check it.

**Comment by chappy84** [comment]
@cybergarage it would be good to get a retract statement in the `go.mod` file, as per this: https://go.dev/doc/modules/gomod-ref#retract for v0.8.3, that way go knows not to allow that version to be used anywhere 🙂
